name: Run JavaScript Program On-Demand

on:
  schedule:
    # Add comment
     - cron: '0 */2 * * *'
  workflow_dispatch: {}
jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
    # Checks out the repository's code
      - name: Checkout code
        uses: actions/checkout@v3

      # Sets up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Runs your JavaScript file (example: app.js)
      - name: Run JavaScript Program
        run: node main.js
        env:
          BOUNTY_WEBHOOK_SECRET: ${{ secrets.BOUNTY_WEBHOOK_SECRET }}
